### ISSUE TITLE
请问学长还能回想起去年考试更具体的内容吗？

### ISSUE THREAD

**Issue by hit-lance** [1160300314/Compiler_2019Spring#1]
大三学弟求助，最近快考编译期末了，学长的仓库对我的复习起到了很大的指引作用，先在这里谢谢了。学长提到去年考到了“一道修改或者自行设计翻译方案的题目”，请问这道题目的难度怎么样？具体问的是什么学长还能回忆起来吗？或者说题目类型和难度与习题9.3还是13.1更接近呢？感觉9.3要简单很多，13.1要麻烦一些。
![U3_MB3ZGTU3~60N2L}31OV8](https://user-images.githubusercontent.com/57555256/86384465-59d40a80-bcc1-11ea-9315-2e87fb4b7d3b.png)
![Q7_SGC5Q ~8OJ5}6W_R%SWA](https://user-images.githubusercontent.com/57555256/86384470-5c366480-bcc1-11ea-80e4-b4ebf76ad7ab.png)

**Comment by MingyanZHU** [comment]
**很抱歉，最近发现自己仓库里有issues**
关于你的问题
1. 不难，去年卷子整体上也不难。
2. 具体问的什么我已经没有印象了。
3. 题目我的感觉是和9.3更加接近，但是在询问了我室友、同学之后，他们感觉不太像，所以我也不能给出确定答案。

可能对你的关心的问题帮助不大，但衷心地希望你的努力在这门课上有所收获。

**Comment by hit-lance** [comment]
我明白了，谢谢学长能抽出时间回答，您的解答对我来说非常有帮助。祝学长研究生学习顺利，生活愉快~
